config/routes.rb
Rails.application.routes.draw do
  

  resources :order_items
  resources :orders
  resources :search
  get '/seller/confirm/:id ', to: 'seller#confirm', as: 'confirm'
  get '/seller/deliver/:id ', to: 'seller#deliver', as: 'deliver'
  get '/add_to_cart/addItem/:id ', to: 'home#addItem', as: 'addItem'
  resources :seller
  resources :user_coupones
  resources :coupones
  resources :orders do
    collection do
      get :update_order, :as => :update_order
    end   
  end
  resources :cart_items
  resources :products do
    resources :reviews, except: [:show, :index]
  end  
  resources :stores
  resources :categories
  resources :brands
  resources :carts do
    collection do
      get :update_quantity, :as => :update_quantity
      get :do_checkout, :as => :do_checkout
      get :take_coupone_code, :as=>:take_coupone_code
      get :cart_delete, :as=>:cart_delete
    end   
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root :to => "home#index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)
    if user.seller?
      can :manage, Product
      can :manage, '/seller'
    elsif user.buyer?
      can :manage, Cart
      can :manage, Order
    else
      can :read, :Product
    end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :products

    validates :name, presence: true, format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" }
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items
  has_many :products, through: :cart_items

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

end

app/models/category.rb
class Category < ApplicationRecord
    
    has_many :products
    validates :name, presence: true, format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" }
    
end

app/models/city.rb
class City < ApplicationRecord
    belongs_to :country 
    has_many :orders  
end

app/models/country.rb
class Country < ApplicationRecord
    has_many :cities
    has_many :orders
end

app/models/coupone.rb
class Coupone < ApplicationRecord

    enum coupone_type: [:fixed, :discount]
    enum expiration_type: [:time, :no_of_usage]
    enum status: [:available, :unvailable]

    has_many :user_coupones 
    has_many :users, through: :user_coupones

    validates :coupone_type, presence: true, format: { with: /\A[a-zA-Z]+\z/,
    message: "you must select an option" }
    validates :value, presence: true

    validates :expiration_type, presence: true
    
    validates :code, presence: true
    validates :status, presence: true

end

app/models/order.rb
class Order < ApplicationRecord
  enum order_status: [:Pending, :Confirmed, :Delivered]
  belongs_to :cart
  has_many :carts
  has_many :order_items
  has_many :products, through: :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  enum status: [:Pending, :Confirmed, :Delivered]
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store
  belongs_to :category
  belongs_to :brand
  belongs_to :user
  has_many :cart_items
  has_many :carts, through: :cart_items
  has_many :order_items
  has_many :orders, through: :order_items
  has_one_attached :image 
  has_many :reviews

  def self.search(term, search_term)
    if term
      if search_term == "0"
        where('title LIKE ?', "%#{term}%")
      elsif search_term == "1"
        where('description LIKE ?', "%#{term}%")
      end
    else
      all
    end
  end

  def self.filter(category_id, brand_id, seller_id)
    if category_id
      where('category_id LIKE ?', "%#{category_id}%")
    elsif brand_id
      where('brand_id LIKE ?', "%#{brand_id}%")
    elsif seller_id
      where('seller_id LIKE ?', "%#{seller_id}%")
    else
      all
    end
  end

end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :product
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  has_many :products

  validates :name, presence: true, format: { with: /\A[a-zA-Z]+\z/,
  message: "must be character format" }
  validates :summary, presence: true, format: { with: /\A[a-zA-Z]+\z/,
  message: "must be character format" }

  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   enum role: [:admin, :seller, :buyer]
   has_many :products
   has_one :store
   has_one :cart
   has_many :user_coupones 
   has_many :coupones, through: :user_coupones
   has_many :reviews, dependent: :destroy
   has_one_attached :avatar
end

app/models/user_coupone.rb
class UserCoupone < ApplicationRecord
  belongs_to :coupone
  belongs_to :user
end

app/controllers/stores_controller.rb
class StoresController < InheritedResources::Base

  def index
    @stores = Store.all
  end
   
  def show
      @store = Store.find(params[:id])
  end
  def new
    @store = Store.new
  end
  def edit
    @store = Store.find(params[:id])
  end

  def create
    @store = Store.new(store_params)
      if  @store .save
          redirect_to  @store 
      else
        render 'new'
      end
  end

  def update
    @store  = Store.find(params[:id])
 
    if   @store .update(store_params)
      redirect_to   @store
    else
      render 'edit'
    end
  end
 
  def destroy
    @store  = Store.find(params[:id])
    @store .destroy
 
    redirect_to stores_path
  end

  private

    def store_params
      params.require(:store).permit(:name, :summary, :user_id)
    end

end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/seller_helper.rb
module SellerHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <br>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <br>
    <%= form.text_area :summary %>
  </div>
  
  <div class="md-form">
    <%= form.label :user_id %>
    <br>
    <%= form.select :user_id, ("<option></option>" + options_from_collection_for_select(User.all, :id, :name, )).html_safe %>
  </div>
  <br>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Summary</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.summary %></td>
        <td><%= store.user %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @store.summary %>
</p>

<p>
  <strong>User:</strong>
  <%= @store.user.name %>
  
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>