config/routes.rb
Rails.application.routes.draw do
  

  resources :order_items
  resources :orders
  resources :search
  get '/seller/confirm/:id ', to: 'seller#confirm', as: 'confirm'
  get '/seller/deliver/:id ', to: 'seller#deliver', as: 'deliver'
  get '/add_to_cart/addItem/:id ', to: 'home#addItem', as: 'addItem'
  resources :seller
  resources :user_coupones
  resources :coupones
  resources :orders do
    collection do
      get :update_order, :as => :update_order
    end   
  end
  resources :cart_items
  resources :products do
    resources :reviews, except: [:show, :index]
  end  
  resources :stores
  resources :categories
  resources :brands
  resources :carts do
    collection do
      get :update_quantity, :as => :update_quantity
      get :do_checkout, :as => :do_checkout
      get :take_coupone_code, :as=>:take_coupone_code
      get :cart_delete, :as=>:cart_delete
    end   
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root :to => "home#index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)
    if user.seller?
      can :manage, Product
      can :manage, '/seller'
    elsif user.buyer?
      can :manage, Cart
      can :manage, Order
    else
      can :read, :Product
    end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :products

    validates :name, presence: true, format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" }
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items
  has_many :products, through: :cart_items

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

end

app/models/category.rb
class Category < ApplicationRecord
    
    has_many :products
    validates :name, presence: true, format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" }
    
end

app/models/city.rb
class City < ApplicationRecord
    belongs_to :country 
    has_many :orders  
end

app/models/country.rb
class Country < ApplicationRecord
    has_many :cities
    has_many :orders
end

app/models/coupone.rb
class Coupone < ApplicationRecord

    enum coupone_type: [:fixed, :discount]
    enum expiration_type: [:time, :no_of_usage]
    enum status: [:available, :unvailable]

    has_many :user_coupones 
    has_many :users, through: :user_coupones

    validates :coupone_type, presence: true, format: { with: /\A[a-zA-Z]+\z/,
    message: "you must select an option" }
    validates :value, presence: true

    validates :expiration_type, presence: true
    
    validates :code, presence: true
    validates :status, presence: true

end

app/models/order.rb
class Order < ApplicationRecord
  enum order_status: [:Pending, :Confirmed, :Delivered]
  belongs_to :cart
  has_many :carts
  has_many :order_items
  has_many :products, through: :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  enum status: [:Pending, :Confirmed, :Delivered]
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store
  belongs_to :category
  belongs_to :brand
  belongs_to :user
  has_many :cart_items
  has_many :carts, through: :cart_items
  has_many :order_items
  has_many :orders, through: :order_items
  has_one_attached :image 
  has_many :reviews

  def self.search(term, search_term)
    if term
      if search_term == "0"
        where('title LIKE ?', "%#{term}%")
      elsif search_term == "1"
        where('description LIKE ?', "%#{term}%")
      end
    else
      all
    end
  end

  def self.filter(category_id, brand_id, seller_id)
    if category_id
      where('category_id LIKE ?', "%#{category_id}%")
    elsif brand_id
      where('brand_id LIKE ?', "%#{brand_id}%")
    elsif seller_id
      where('seller_id LIKE ?', "%#{seller_id}%")
    else
      all
    end
  end

end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :product
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  has_many :products

  validates :name, presence: true, format: { with: /\A[a-zA-Z]+\z/,
  message: "must be character format" }
  validates :summary, presence: true, format: { with: /\A[a-zA-Z]+\z/,
  message: "must be character format" }

  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   enum role: [:admin, :seller, :buyer]
   has_many :products
   has_one :store
   has_one :cart
   has_many :user_coupones 
   has_many :coupones, through: :user_coupones
   has_many :reviews, dependent: :destroy
   has_one_attached :avatar
end

app/models/user_coupone.rb
class UserCoupone < ApplicationRecord
  belongs_to :coupone
  belongs_to :user
end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base

  def show
        
    @product = Product.find params[:id]
    @product_cat = Product.includes(:category).find(params[:id])
    
    @product_store = Product.includes(:store).find(params[:id])
    @product_brand = Product.includes(:brand).find(params[:id])
    @reviews = Review.where(product_id: @product.id).order("created_at DESC")
  end
  
  def new
    @stores = Store.all
    @categories = Category.all
    @brands = Brand.all
    @product = Product.new
    #render plain: @users.inspect
  end

  def edit
    @stores = Store.all
    @categories = Category.all
    @brands = Brand.all
    @product = Product.find(params[:id])
    end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    @user =current_user.id
    @product.store=Store.select(:id).where(user_id: @user).first
    if @product.save
        redirect_to @product
    else
        render 'new'
    end
  end

  private

    def product_params
      params.require(:product).permit(:title, :description, :price, :quantity, :image, :store_id, :category_id, :brand_id, :user_id)
    end

end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/seller_helper.rb
module SellerHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title ,class:"form-control"%>
  </div>

  <br>
<br>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description ,class:"form-control"%>
  </div>

  <br>
  <br>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price ,class:"form-control"%>
  </div>

  <br>
<br>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity ,class:"form-control"%>
  </div>

  <br>
  <br>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.collection_select(:category_id, Category.all, :id, :name, :include_blank => "Please select category") %>
  </div>

<br>
<br>

  <div class="field">
    <%= form.label :brand_id %>
    <%= form.collection_select(:brand_id, Brand.all, :id, :name, :include_blank => "Please select brand") %>
  </div>

  <br>
  <br>

  <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
  </div>






























































  
  <br>
  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Image</th>
      <th>Store</th>
      <th>Category</th>
      <th>Brand</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.quantity %></td>
        <td><%= image_tag(product.image, class:'img-fluid w-100', style:'width:30px ; height:30px') if product.image.attached?  %></td>
        <td><%= product.store.name %></td>
        <td><%= product.category.name %></td>
        <td><%= product.brand.name %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<!--================Home Banner Area =================-->
<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
      <div class="container">
        <div
          class="banner_content d-md-flex justify-content-between align-items-center"
        >
          <div class="mb-3 mb-md-0">
            <h2>Product Details</h2>
            <p>Very us move be blessed multiply night</p>
          </div>
          <div class="page_link">
            <a href="index.html">Home</a>
            <a href="single-product.html">Product Details</a>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--================End Home Banner Area =================-->
    <!--================Single Product Area =================-->
    <div class="product_image_area">
        <div class="container">
          <div class="row s_product_inner">
            <div class="col-lg-6">
              <div class="s_product_img">
                <div
                  id="carouselExampleIndicators"
                  class="carousel slide"
                  data-ride="carousel"
                >
                  <div class="carousel-inner">
                    <div class="carousel-item active">
                      <%= link_to image_tag @product.image , :class => "carousel-item active" , :alt =>"First slide"%>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-5 offset-lg-1">
              <div class="s_product_text">
                <h3> <%= @product.title %></h3>
                <h2>$ <%= @product.price %></h2>
                <ul class="list">
                  <li>
                    <a class="active" href="#">
                      <span>Category</span> : <%= @product_cat.category.name %></a
                    >
                  </li>
                  <li>
                    <a href="#"> <span>Availibility</span> : In Stock</a>
                  </li>
                </ul>
                <p>
                  store name: <%= @product_store.store.name %> <br>
                  brand name: <%= @product_brand.brand.name %> 
                </p>
                <div class="product_count">
                  <label for="qty">Quantity:</label>
                  <input
                    type="text"
                    name="qty"
                    id="sst"
                    maxlength="12"
                    value="1"
                    title="Quantity:"
                    class="input-text qty"
                  />
                  <button
                    onclick="var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst )) result.value++;return false;"
                    class="increase items-count"
                    type="button"
                  >
                    <i class="lnr lnr-chevron-up"></i>
                  </button>
                  <button
                    onclick="var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst ) &amp;&amp; sst > 0 ) result.value--;return false;"
                    class="reduced items-count"
                    type="button"
                  >
                    <i class="lnr lnr-chevron-down"></i>
                  </button>
                </div>
                <div class="card_area">
                  <a class="main_btn" href="#">Add to Cart</a>
                  <a class="icon_btn" href="#">
                    <i class="lnr lnr lnr-diamond"></i>
                  </a>
                  <a class="icon_btn" href="#">
                    <i class="lnr lnr lnr-heart"></i>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!--================End Single Product Area =================-->
  
      <!--================Product Description Area =================-->
      <section class="product_description_area">
        <div class="container">
          <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
              <a
                class="nav-link"
                id="home-tab"
                data-toggle="tab"
                href="#home"
                role="tab"
                aria-controls="home"
                aria-selected="true"
                >Description</a
              >
            </li>
            </li>
            <li class="nav-item">
              <a
                class="nav-link active"
                id="review-tab"
                data-toggle="tab"
                href="#review"
                role="tab"
                aria-controls="review"
                aria-selected="false"
                >Reviews</a
              >
            </li>
          </ul>
          <div class="tab-content" id="myTabContent">
            <div
              class="tab-pane fade"
              id="home"
              role="tabpanel"
              aria-labelledby="home-tab"
            >
              <p>
                  <%= @product.description %>
              </p>
            </div>
            <div
              class="tab-pane fade"
              id="profile"
              role="tabpanel"
              aria-labelledby="profile-tab"
            >
            </div>
            <div
              class="tab-pane fade"
              id="contact"
              role="tabpanel"
              aria-labelledby="contact-tab"
            >
              <div class="row">
                <div class="col-lg-6">
                  <div class="comment_list">
                    <div class="review_item">
                      <div class="media">
                        <div class="d-flex">
                          <img
                            src="img/product/single-product/review-3.png"
                            alt=""
                          />
                        </div>
                        <div class="media-body">
                          <h4>Blake Ruiz</h4>
                          <h5>12th Feb, 2017 at 05:56 pm</h5>
                          <a class="reply_btn" href="#">Reply</a>
                        </div>
                      </div>
                      <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                        sed do eiusmod tempor incididunt ut labore et dolore magna
                        aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                        ullamco laboris nisi ut aliquip ex ea commodo
                      </p>
                    </div>
                  </div>
                </div>
                <div class="col-lg-6">
                  <div class="review_box">
                    <h4>Post a comment</h4>
                    <form
                      class="row contact_form"
                      action="contact_process.php"
                      method="post"
                      id="contactForm"
                      novalidate="novalidate"
                    >
                      <div class="col-md-12">
                        <div class="form-group">
                          <input
                            type="text"
                            class="form-control"
                            id="name"
                            name="name"
                            placeholder="Your Full name"
                          />
                        </div>
                      </div>
                      <div class="col-md-12">
                        <div class="form-group">
                          <input
                            type="email"
                            class="form-control"
                            id="email"
                            name="email"
                            placeholder="Email Address"
                          />
                        </div>
                      </div>
                      <div class="col-md-12">
                        <div class="form-group">
                          <input
                            type="text"
                            class="form-control"
                            id="number"
                            name="number"
                            placeholder="Phone Number"
                          />
                        </div>
                      </div>
                      <div class="col-md-12">
                        <div class="form-group">
                          <textarea
                            class="form-control"
                            name="message"
                            id="message"
                            rows="1"
                            placeholder="Message"
                          ></textarea>
                        </div>
                      </div>
                      <div class="col-md-12 text-right">
                        <button
                          type="submit"
                          value="submit"
                          class="btn submit_btn"
                        >
                          Submit Now
                        </button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
            <div
              class="tab-pane fade show active"
              id="review"
              role="tabpanel"
              aria-labelledby="review-tab"
            >
              <div class="row">
                <div class="col-lg-6">
       
                <div class="review_list">
                    <% if @reviews.blank? %>
                    <h3>No reviews just yet, would you like to add the first!</h3>
                    <%= link_to "Write Review", new_product_review_path(@product), class: "btn btn-danger" %>
                  <% else %>
                  <% @reviews.each do |review| %>
                    <div class="review_item">
                      <div class="media">
                        <div class="d-flex">
                          <img
                            src="img/product/single-product/review-1.png"
                            alt=""
                          />
                        </div>
                        <div class="media-body">
                          <h4><%= review.user.name %></h4>
                          <i class="fa fa-star"><%= review.rating%></i>
                        </div>
                      </div>
                      <p>
                          <%= review.comment%>
                      </p>
                    </div>
                    <% end %>
                    <% end %>
                </div>
              </div>

                <div class="col-lg-6">
                  <div class="review_box">
                    <h4>Add a Review</h4>
                    <p>Your Rating:</p>
                    <ul class="list">
                      <li>
                        <a href="#">
                          <i class="fa fa-star"></i>
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-star"></i>
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-star"></i>
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-star"></i>
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-star"></i>
                        </a>
                      </li>
                    </ul>
                    <p>Outstanding</p>
                    <%= link_to "create review" , new_product_review_path(@product), class: "btn submit_btn" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

    